### ISSUE TITLE
Auto code update in docker container not working.

### ISSUE THREAD

**Issue by sultanfendonus** [StephenGrider/docker-react#3]
Every time I need to run this line for update code in the docker container.
`docker-compose up --build`

**docker-compose.yml**
```
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "4006:3000"
    volumes:
      - /app/node_modules
      - .:/app
```
**Dockerfile.dev**
```
FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]
```

 I completely follow your code but not working. Help!

**Comment by sultanfendonus** [comment]
Even I clone your repo still not working.

**Comment by MatinSasan** [comment]
Quoted from him: 

If you are running on Windows, please read this: Create-React-App has some issues detecting when files get changed on Windows based machines.  To fix this, please do the following:

1)In the root project directory, create a file called .env

2)Add the following text to the file and save it: CHOKIDAR_USEPOLLING=true

3)That's all! 

------
However for me is that live update for testing doesn't work: 

```
tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: npm test

```
